### ISSUE TITLE
Matlab from docker-compose

### ISSUE THREAD

**Issue by sfl0r3nz05** [mathworks-ref-arch/matlab-dockerfile#39]
Hi all,

I can connect to Matlab on docker via VNC using this command:
```
docker run -it --rm -e PASSWORD=XXXXXX -p 5901:5901 -p 6080:6080 --shm-size=512M mathworks/matlab:r2021b -vnc
```

However, I want to deploy Matlab as part of a set of containers using docker-compose. Thus, I have tried declaring VNC as an environment and it does not work (NOVNC is not defined as an environment variable in [docker hub](https://hub.docker.com/r/mathworks/matlab))

```
  matlab:
    image: mathworks/matlab:r2021b
    shm_size: 512M
    ports:
      - "5901:5901"
      - "6080:6080"
    environment:
      NOVNC: "true"
      PASSWORD: "XXXXXX"
```

Is there a way to enable the VNC server from docker-compose?

Thanks in advance,

Santiago.

**Comment by josmartin** [comment]
Use the [command configuration option](https://docs.docker.com/compose/compose-file/compose-file-v3/#command) to specify arguments after the enrtypoint. Also do not define the environment variable `NOVNC` since that tells the container NOT to start VNC.
```
services:
  matlab:
    image: mathworks/matlab:r2021b
    shm_size: 512M
    ports:
      - "5901:5901"
      - "6080:6080"
    environment:
      PASSWORD: "XXXXXX"
    command: -vnc
````
