### ISSUE TITLE
Gitlab-CI: Matlab asks for license credentials since 2023b although the container was called like the one for 2023a

### ISSUE THREAD

**Issue by GenosseFlosse** [mathworks-ref-arch/matlab-dockerfile#76]
Hey there!

I am using matlab containers as described in [building-on-matlab-docker-image](https://github.com/mathworks-ref-arch/matlab-dockerfile/tree/main/alternates/building-on-matlab-docker-image#building-on-matlab-docker-image). 

My Gitlab-CI calls:
```
.test-image:
  stage: test
  tags:
    - docker
  variables:
    VER: r2023b # is overridden in job call to test multiple matlab versions (2020b, 23a, 23b, latest)
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:test_$VER
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$VER
  image: 
    name: $CONTAINER_TEST_IMAGE
    entrypoint: [""]
  script:
    - matlab -batch test
    - test -e testres.mat
  artifacts:
    paths:
      - testres.mat
```

Curiously, until 2023a, everything is working okay. But using 2023b, matlab does not use the network license I provide but instead asks me to put in an E-Mail address. 
To further debug the issue I ran the container for 2023b on Docker Desktop:
```
docker run gitlab.example.com/docker/docker_matlab_gurobi:test_latest matlab -batch rand
Please enter your MathWorks Account email address and press Enter:
Sign-in failed. Would you like to retry? y/n [n]
```
This is the same behaviour I encounter in Gitlab CI

Running the container for 2023a on Docker Desktop:
```
docker run  gitlab.example.com/docker/docker_matlab_gurobi:test_r2023a matlab -batch rand
ans =

    0.8147
```
This is also the same behaviour I encounter for 2023a in the Gitlab CI.

So here is what I don't understand: Why does one container work and the other doesn't although everything is configured the same and called the same? Did something change in the default entrypoint?
